name: "Get Sales Events"
on:
  # schedule:
  # - cron: "*/25 * * * *"
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    permissions: write-all
    timeout-minutes: 25
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install -r requirements.txt
      
      - name: Get sales and average price
        env:
            ADDRESS: ${{ secrets.ADDRESS }}
            URL_MONGODB: ${{ secrets.URL_MONGODB }}
            API_KEY: ${{ secrets.API_KEY }}
            API_KEY_2: ${{ secrets.API_KEY_2 }}
            DATABASE: ${{ secrets.DATABASE }}
            COLLECTION: ${{ secrets.COLLECTION }}
        run: |
          python3 check_sales_events.py
          echo "## Getting sales events" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY