name: "Update Collections"
on:
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    environment: production
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install -r requirements-2.txt
      
      - name: Update collections
        env:
            GS_CREDENTIALS: ${{ secrets.GS_CREDENTIALS }}
            URL_MONGODB: ${{ secrets.URL_MONGODB }}
        run: |
          python3 update_collections.py
          echo "## Updating collections" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY